---
- hosts: all
  become: true
  tasks:
    - name: Update package index for RedHat
      yum:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "RedHat"

    - name: Update package index for Ubuntu
      apt:
        name:
          - apache2
          - php
        state: latest
      when: ansible_distribution == "Ubuntu"

