---
- hosts: all
  become: true
  tasks:
    - name: Remove Apache package for RHEL
      yum:
        name:
          - httpd
          - php
        state: absent
      when: ansible_distribution == "RedHat"

    - name: Remove Apache package for Ubuntu
      apt:
        name:
          - apache2
          - php
        state: absent
      when: ansible_distribution == "Ubuntu"

    - name: Remove MySQL Server package
      apt:
        name:
          - mysql-server
        state: absent
      when: ansible_distribution == "Ubuntu"

