---
- hosts: all
  become: true
  tasks:
    - name: Update package index
      package:
        update_cache: yes
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "RedHat"


- hosts: web_server
  become: true
  tasks:

    - name: Install apache for RedHat
      yum:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "RedHat"

    - name: Install apache for Ubuntu
      apt:
        name:
          - apache2
          - php
        state: latest
      when: ansible_distribution == "Ubuntu"


- hosts: database
  become: true
  tasks:

    - name: Intall SQL on Ubuntu Server
      apt:
        name:
          - mysql-server
      when: ansible_distribution == "Ubuntu"



